RACE_FEATURES = [
    "raceId",
    "meetingId",
    "raceNumber",
    "raceTypeCode",
    "raceStartHour",
    "raceStartMinute",
    "owningAuthorityCode",
    "distance",
    "prizeMoneyTotal",
]

RUN_FEATURES = [
    "run_trackCode",
    "run_dogId",
    "run_weightInKg",
    "run_incomingGrade",
    "run_outgoingGrade",
    "run_gradedTo",
    "run_rating",
    "run_boxNumber",
    "run_runId",
    "run_rugNumber",
    "run_startPrice",
    "run_scratched",
    "run_isLateScratching",
    "run_colourCode",
    "run_sex",
    "run_ownerId",
    "run_ownerState",
    "run_trainerName",
    "run_trainerState",
    "run_trainerSuburb",
    "run_trainerPostCode",
    "run_damId",
    "run_isWinner",
]

FORM_FEATURES = [
    "form_bestFinishTrackAndDistance",
    "form_careerPrizeMoney",
    "form_averageSpeed",
    "form_totalFormCount",
    "form_bestFinishTrackDistance",
    "form_bestFirstSplitTrackDistance",
    "form_avgFirstSplitTrackDistance",
    "form_bestFirstSplitTrackDistanceBox",
]

LAST_RACE_FEATURES = [f"run_last_race_{i+1}" for i in range(5)]

FORM_STATISTICS_FEATURES = [
    f"form_formStatistics_{stat}"
    for stat in [
        "career_starts",
        "career_first",
        "career_second",
        "career_third",
        "sprint_starts",
        "sprint_first",
        "sprint_second",
        "sprint_third",
        "main_starts",
        "main_first",
        "main_second",
        "main_third",
        "staying_starts",
        "staying_first",
        "staying_second",
        "staying_third",
        "track_starts",
        "track_first",
        "track_second",
        "track_third",
        "distance_starts",
        "distance_first",
        "distance_second",
        "distance_third",
        "box_starts",
        "box_first",
        "box_second",
        "box_third",
        "trackDistance_starts",
        "trackDistance_first",
        "trackDistance_second",
        "trackDistance_third",
        "trackDistanceBox_starts",
        "trackDistanceBox_first",
        "trackDistanceBox_second",
        "trackDistanceBox_third",
        "trackBox_starts",
        "trackBox_first",
        "trackBox_second",
        "trackBox_third",
        "trackType_starts",
        "trackType_first",
        "trackType_second",
        "trackType_third",
        "trackTypeBox_starts",
        "trackTypeBox_first",
        "trackTypeBox_second",
        "trackTypeBox_third",
    ]
]

ALL_FEATURES = RACE_FEATURES + RUN_FEATURES + FORM_FEATURES + LAST_RACE_FEATURES + FORM_STATISTICS_FEATURES
